#Number of orders: 1
#Tasks: assembly
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No

options:
  insert_models_over_bins: true
  belt_population_cycles: 0
  insert_models_over_stations: false
  gazebo_state_logging: false
time_limit: 500

agv_infos:
  agv1:
    location: ks1
  agv2:
    location: ks2
  # agv3:
  #   location: ks3
  #   products:
  #     part_0:
  #       type: assembly_pump_green
  #       pose:
  #         xyz: [0.1, 0.1, 0]
  #         rpy: [0, 0, 0]
  
  ## Agility Challegen : Faulty Part 
  agv3:
    location: ks3
  agv4:
    location: ks4   
    
orders:
  # Example for tasking one robot to do assembly and one robot to do kitting
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv3]
      destinations: [as3]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: ['pi', 0, 0]
        part_1:
          type: assembly_battery_green
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [0, 0, 0]
  order_1:
    priority: 3
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: wanted_products
    announcement_condition_value: 1.0
    kitting:
      shipment_count: 1
      agvs: [agv2]
      destinations: [as2]
      products:
        part_0:
          type: assembly_pump_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        # part_1:
        #   type: assembly_sensor_green
        #   pose:
        #     xyz: [-0.1, -0.1, 0]
        #     rpy: [0, 0, 0]

models_over_bins:
  bin1:
     models:
       assembly_battery_green:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
  bin2:
     models:
       assembly_pump_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

# belt_models:
#   assembly_pump_red:
#     10.0:
#       pose:
#         xyz: [0.0, 4.3, 0.92]
#         rpy: [0, 0, 0]

# models_over_stations:
#   as1:
#     models:
#       assembly_battery_blue:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 'pi']
#       assembly_pump_blue:
#         xyz: [0.032085, -0.152835, 0.15]
#         rpy: [0, 0, 0]
#   as2:
#     models:
#       assembly_battery_blue:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 'pi']
#       assembly_pump_blue:
#         xyz: [0.032085, -0.152835, 0.15]
#         rpy: [0, 0, 0]
#   as3:
#     models:
#       assembly_battery_blue:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 'pi']
#       assembly_pump_blue:
#         xyz: [0.032085, -0.152835, 0.15]
#         rpy: [0, 0, 0]
#   as4:
#     models:
#       assembly_battery_blue:
#         xyz: [-0.032465, 0.174845, 0.15]
#         rpy: [0, 0, 'pi']
#       assembly_pump_blue:
#         xyz: [0.032085, -0.152835, 0.15]
#         rpy: [0, 0, 0]

faulty_products:
  - assembly_battery_green_1
  - assembly_battery_green_2
  - assembly_battery_green_3
  - assembly_battery_green_4
  - assembly_pump_red_1
  - assembly_pump_red_2
  - assembly_pump_red_3
  - assembly_pump_red_4

sensor_blackout:
  product_count: 1
  duration: 20
