#Number of orders: 1
#Tasks: assembly
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No

options:
  insert_models_over_bins: true
  belt_population_cycles: 10
  insert_models_over_stations: false
  gazebo_state_logging: false
time_limit: -1

agv_infos:
  agv1:
    location: as1
  agv2:
    location: as1
  agv3:
    location: as3
  agv4:
    location: as3  
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv1]
      destinations: [as1]
      products:
        part_0:
          type: assembly_sensor_red
          pose:
            xyz: [-0.1, 0.1, 0]
            rpy: [0, 0, 'pi/3']
        part_1:
          type: assembly_sensor_red
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 'pi/2']
        # part_2:
        #   type: assembly_battery_blue
        #   pose:
        #     xyz: [0.1, -0.1, 0]
        #     rpy: [0, 0, 0]                
  
  # order_1:
  #   priority: 3
  #   kitting_robot_health: 1 
  #   assembly_robot_health: 1 
  #   announcement_condition: wanted_products
  #   announcement_condition_value: 1
  #   kitting:
  #     shipment_count: 1
  #     agvs: [agv2]
  #     destinations: [as2]
  #     products:
  #       part_0:
  #         type: assembly_battery_blue
  #         pose:
  #           xyz: [0.1, 0.1, 0]
  #           rpy: [0, 0, '-pi/3']

models_over_bins:
  bin1:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2
  bin2:
     models:
       assembly_sensor_red:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

  bin5:
     models:
       assembly_battery_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, 0]
         num_models_x: 2
         num_models_y: 2

belt_models:
  assembly_pump_red:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 0]

faulty_products:
  - assembly_battery_blue_2
  # - assembly_sensor_red_1


# sensor_blackout:
#   product_count: 1
#   duration: 10
