#Number of orders: 1
#Tasks: assembly
#Number of shipments: 1
#Insufficiently many products: No
#Part re-orientation: No
#In-process order update: No
#Dropped products: No
#In-process order interruption: No
#Faulty products: No
#Sensor blackout: No
#Time limit: No

options:
  insert_models_over_bins: true
  insert_models_over_stations: false
  enable_robot_camera: false
  belt_population_cycles: 10
time_limit: -1


agv_infos:
  agv1:
    location: ks1
  agv2:
    location: as1
    products:
      part_0:
        type: assembly_battery_green
        pose:
          xyz: [0.1, 0.1, 0]
          rpy: [0, 0, 0]
      part_1:
        type: assembly_pump_blue
        pose:
          xyz: [-0.1, -0.1, 0]
          rpy: [pi, 0, pi/2]
  agv3:
    location: ks3
  agv4:
    location: ks4
   
    
orders:
  order_0:
    priority: 1
    kitting_robot_health: 1 
    assembly_robot_health: 1 
    announcement_condition: time
    announcement_condition_value: 0.0
    kitting:
      shipment_count: 1
      agvs: [agv4]
      destinations: [as3]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [0.1, 0.1, 0]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [-0.1, -0.1, 0]
            rpy: [pi, 0, pi/2]
  order_1:
    priority: 1 # default is 1 if omitted, we could omit this line
    kitting_robot_health: 1 
    assembly_robot_health: 1
    announcement_condition: agv_station_reached
    announcement_condition_value: agv4_at_as3
    assembly:
      shipment_count: 2
      stations: [as3, as1]
      products:
        part_0:
          type: assembly_battery_green
          pose:
            xyz: [-0.032465, 0.174845, 0.15]
            rpy: [0, 0, 0]
        part_1:
          type: assembly_pump_blue
          pose:
            xyz: [0.032085, -0.152835, 0.25]
            rpy: [pi, 0, 0]

models_over_bins:
   bin3:
     models:
       assembly_pump_blue:
         xyz_start: [0.1, 0.1, 0.0]
         xyz_end: [0.5, 0.5, 0.0]
         rpy: [0, 0, pi/4]
         num_models_x: 2
         num_models_y: 2
   bin6:
     models:
       assembly_pump_blue:
         xyz_start: [0.2, 0.2, 0.0]
         xyz_end: [0.4, 0.4, 0.0]
         rpy: [0, 0, -pi/4]
         num_models_x: 2
         num_models_y: 2

belt_models:
  assembly_battery_green:
    10.0:
      pose:
        xyz: [0.0, 4.3, 0.92]
        rpy: [0, 0, 'pi/2']

faulty_products:
  - assembly_pump_blue_2
  - assembly_pump_blue_3
  - assembly_pump_blue_6
  - assembly_pump_blue_7

# sensor_blackout:
#   product_count: 3
#   duration: 50

