gantry_torso:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
gantry_arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
gantry_full:
  kinematics_solver: cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin
  # optional parameters for caching:
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  max_cache_size: 10000
  min_pose_distance: 1
  # min_joint_config_distance: 4