# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gantry_full
  joint_model_group_pose: gantry_home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - small_long_joint
    - torso_rail_joint
    - torso_base_main_joint
    - gantry_arm_shoulder_pan_joint
    - gantry_arm_shoulder_lift_joint
    - gantry_arm_elbow_joint
    - gantry_arm_wrist_1_joint
    - gantry_arm_wrist_2_joint
    - gantry_arm_wrist_3_joint
    - gantry_arm_vacuum_gripper_joint
    - torso_main_torso_tray_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: /ariac/gantry/gantry_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - gantry_arm_shoulder_pan_joint
      - gantry_arm_shoulder_lift_joint
      - gantry_arm_elbow_joint
      - gantry_arm_wrist_1_joint
      - gantry_arm_wrist_2_joint
      - gantry_arm_wrist_3_joint
  - name: /ariac/gantry/gantry_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - small_long_joint
      - torso_rail_joint
      - torso_base_main_joint